#PBS -l nodes=1:ppn=7
#PBS -l mem=60GB
#PBS -l walltime=00:20:00
#PBS -S /bin/bash
#PBS -N anom
#PBS -o logs/anom_2_out.txt
#PBS -e logs/anom_2_err.txt

source /home/scrd102/cccma_libs/cccma/latest/config/computational_environment
source /fs/homeu3/eccc/crd/ords/cccma/reo000/uvenvs/py312u3/bin/activate

cd /home/reo000/projects/MHW/MHW_Forecasts_2608
python MHW_daily_calcs.py calcAnom_CanESM5 2
echo 'end'
