#PBS -l nodes=1:ppn=1
#PBS -l mem=20GB
#PBS -l walltime=03:00:00
#PBS -S /bin/bash
#PBS -N o1d5d
#PBS -o logs/o1d5d_out.txt
#PBS -e logs/o1d5d_err.txt

source /home/scrd102/cccma_libs/cccma/latest/config/computational_environment
source /fs/homeu3/eccc/crd/ords/cccma/reo000/uvenvs/py312u3/bin/activate

cd /home/reo000/projects/MHW/MHW_Forecasts_2608
python MHW_daily_calcs.py daily_to_5day_OISST
echo 'end'
