#PBS -l nodes=1:ppn=7
#PBS -l mem=30GB
#PBS -l walltime=06:00:00
#PBS -S /bin/bash
#PBS -N anombylead
#PBS -o logs/anombylead_out.txt
#PBS -e logs/anombylead_err.txt

source /home/scrd102/cccma_libs/cccma/latest/config/computational_environment
source /fs/homeu3/eccc/crd/ords/cccma/reo000/uvenvs/py312u3/bin/activate

cd /home/reo000/projects/MHW/MHW_Forecasts_New
python MHW_daily_calcs.py anom_bylead
echo 'end'
