#PBS -l nodes=1:ppn=1
#PBS -l mem=12GB
#PBS -l walltime=03:00:00
#PBS -S /bin/bash
#PBS -N MHWSdaily
#PBS -o MHWS_out^array_index^.txt
#PBS -e MHWS_err^array_index^.txt
#PBS -J 0-42

source /home/reo000/myconda
conda activate py12MHW

cd /home/reo000/projects/MHW/MHW_Forecasts_New
python MHW_daily_calcs.py MHW_calc $PBS_ARRAY_INDEX 1 qt1
python MHW_daily_calcs.py MHW_calc $PBS_ARRAY_INDEX 1 qt2
echo 'end'
