## MHW_daily_calcs.py
#PBS -l nodes=1:ppn=1
#PBS -l mem=16GB
#PBS -l walltime=03:00:00
#PBS -S /bin/bash
#PBS -N MHWO
#PBS -o logs/MHWO_out.txt
#PBS -e logs/MHWO_err.txt

source /home/scrd102/cccma_libs/cccma/latest/config/computational_environment
source /fs/homeu3/eccc/crd/ords/cccma/reo000/uvenvs/py312u3/bin/activate
cd /home/reo000/projects/MHW/MHW_Forecasts_New
python MHW_daily_calcs.py MHW_calc_OISST
echo 'end'
